[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Fern Zapata"},
]
license = {text = "GPL-3.0-or-later"}
readme = "README.md"

requires-python = ">=3.8"
dependencies = [
    "qmk>=1.1.2",
]
